global:
  scrape_interval: 5s
  evaluation_interval: 5s

scrape_configs:
  - job_name: 'blockchain-indexer'
    metrics_path: /metrics
    scheme: http
    static_configs:
      - targets: ['blockchain-indexer:9100'] # TODO: Make this dynamic
        labels:
          environment: 'development'