# RabbitMQ Configuration
rabbitmq:
  default_user: myuser
  default_pass: mypassword
  host: rabbitmq
  port: 5672
  management_port: 15672
  queue_name: blocks


# Chain Configuration
chain:
  name: ethereum
  rpc:
    https: 'https://eth.llamarpc.com'
    wss: 'wss://ethereum.publicnode.com'
  # type: 'historical' # Can be 'historical or real-time'
  # block:
  #   start: 0
  #   end: 100000


# Data Output Configuration
data:
  type: local  # Can be 'local' or 'cloud'
  local:
    destination: '/data'
  cloud:
    destination: 'your_cloud_bucket_location'
    credentials:
      access_key: 'your_access_key'
      secret_key: 'your_secret_key'
  chunk_size: 100


# Log Configuration
logging:
  to_file: true # If true, logs will be saved to a file. If false, logs are only printed to console.
  type: local  # Can be 'local' or 'cloud'
  local:
    destination: '/application.log'
  cloud:
    destination: 'your_cloud_bucket_location'
    credentials:
      access_key: 'your_access_key'
      secret_key: 'your_secret_key'