chain:
  name: "ethereum"
  rpc_urls:
    - "https://eth.llamarpc.com"
    - "https://rpc.ankr.com/eth"
    - "https://eth.drpc.org"


# chain:
#   name: "arbitrum"
#   rpc_urls:
#     - "https://arbitrum.llamarpc.com"
#     - "https://rpc.ankr.com/arbitrum"
#     - "https://arbitrum.gateway.tenderly.co"

# chain:
#   name: "cronos_zkevm"
#   rpc_urls:
#     - "https://mainnet.zkevm.cronos.org"

# chain:
#   name: "zksync"
#   rpc_urls:
#     - "https://mainnet.era.zksync.io"
#     - "https://zksync.meowrpc.com"
#     - "https://1rpc.io/zksync2-era"

# chain:
#   name: "zksync_sepolia"
#   rpc_urls:
#     - "https://zksync-sepolia.drpc.org"
#     - "https://sepolia.era.zksync.dev"
