# RabbitMQ Configuration
rabbitmq:
  default_user: myuser
  default_pass: mypassword
  host: rabbitmq
  port: 5672
  management_port: 15672
  queue_name: blocks


# Chain Configuration
chain:
  name: 'ethereum'
  rpc:
    https: 'https://ethereum.publicnode.com'
    wss: 'wss://ethereum.publicnode.com'


# Data Output Configuration
data:
  type: 'local'  # Can be 'local' or 'cloud'
  local:
    destination: '/data'
  cloud:
    destination: 'your_cloud_bucket_location'
    credentials:
      access_key: 'your_access_key'
      secret_key: 'your_secret_key'


# Log Configuration
log:
  to_file: true # If true, logs will be saved to a file. If false, logs are only printed to console.
  type: 'local'  # Can be 'local' or 'cloud'
  local:
    destination: '/logs/application.log'
  cloud:
    destination: 'your_cloud_bucket_location'
    credentials:
      access_key: 'your_access_key'
      secret_key: 'your_secret_key'