# RabbitMQ Configuration
rabbitmq:
  default_user: myuser
  default_pass: mypassword
  host: rabbitmq
  port: 5672
  management_port: 15672
  queue_name: blocks


# Chain Configuration
chain:
  name: 'ethereum'
  rpc:
    # https: 'https://eth.llamarpc.com'
    https: 'https://mainnet.era.zksync.io'
    wss: 'wss://ethereum.publicnode.com'
  block:
    start: 10000000
    end: 10001000


# Data Output Configuration
data:
  type: 'local'  # Can be 'local' or 'cloud'
  local:
    destination: '/data'
  cloud:
    destination: 'your_cloud_bucket_location'
    credentials:
      access_key: 'your_access_key'
      secret_key: 'your_secret_key'
  chunk_size: 1000


# Log Configuration
logging:
  to_file: true # If true, logs will be saved to a file. If false, logs are only printed to console.
  type: 'local'  # Can be 'local' or 'cloud'
  local:
    destination: '/application.log'
  cloud:
    destination: 'your_cloud_bucket_location'
    credentials:
      access_key: 'your_access_key'
      secret_key: 'your_secret_key'