services:
  indexer:
    build: .
    container_name: blockchain-indexer
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 2G
        reservations:
          cpus: '0.5'
          memory: 1G
    volumes:
      - ./config.yml:/app/config.yml
      - ./logs:/app/logs
      - ~/.config/gcloud/application_default_credentials.json:/root/.config/gcloud/application_default_credentials.json
    restart: unless-stopped