services:
  indexer:
    build: .
    container_name: blockchain-indexer
    ports:
      - "9100:9100" # TODO: Make this dynamic
    volumes:
      - ./config.yml:/app/config.yml
      - ./logs:/app/logs
      - ~/.config/gcloud/application_default_credentials.json:/root/.config/gcloud/application_default_credentials.json
    networks:
      - monitoring
    restart: unless-stopped

networks:
  monitoring:
    external: true
    name: monitoring
