image:
  # repository: us-docker.pkg.dev/matterlabs-infra/matterlabs-docker/prover-autoscaler
  tag: latest
  pullPolicy: Always

command:
  # - /usr/bin/zksync_prover_autoscaler
args:
  # - --config-path=/etc/prover-autoscaler-config/config.yaml

probes:
  liveness:
    enabled: false
  startup:
    enabled: false
  readiness:
    enabled: false

service:
  main:
    enabled: true
    ports:
      metrics:
        enabled: true
        port: 8080

serviceMonitor:
  enabled: true
  port: "metrics"
  path: "/metrics"