global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'blockchain-indexer'
    metrics_path: /metrics
    scheme: http
    static_configs:
      - targets: ['blockchain-indexer:8000']
        labels:
          environment: 'development'
          chain: 'ethereum'
        